server:
  port: 8081

jwt:
  secret: secret
  expiration: 100000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/printify
    username: samuel
    password: helloworld

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
#
#
#  thymeleaf:
#    prefix: /home/samuel/IdeaProjects/printify-backend/printify-backend/target/classes/static